version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress preinstalled
      - image: cypress/internal:cy-0.19.4
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: npm run test-multiple
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
